### ISSUE TITLE
Front-End Intermediate Code / Intermediate Syntaxic Code

### ISSUE THREAD

**Issue by schmouk** [Typee-Language/Typee#20]
Deliver all the stuff related to the syntaxic code finally generated by the parser after its syntaxic pass and before its types infering-and-checking step.

**Comment by PhHays** [comment]
CAUTION: this has to be done according to the last (and new) version of Typee design document.
Let's wait for issue #45 to be completed before doing anything: a new directories tree structure has been defined in the design doc of Typee.

**Comment by schmouk** [comment]
Furthermore, this has to be moved into directory 'Commons/'.

**Comment by schmouk** [comment]
Close this issue since it is better described in issue #77
