### ISSUE TITLE
Typee Global S/W Architecture Documentation

### ISSUE THREAD

**Issue by schmouk** [Typee-Language/Typee#45]
We're still lacking a general documentation on __Typee__ software architecture design.
We HAVE to write it, right now!

**Comment by schmouk** [comment]
PhHays, please do!

**Comment by PhHays** [comment]
A first draft revision of the Typee software design has been delivered. Some subsections 5.x still have to be completed, but the current status of the document allows for the coding of next _Python_ modules.
So, we close this #45 issue and we will immediately open a new one for the completion of the missing text.
