### ISSUE TITLE
Typee built-in library Time

### ISSUE THREAD

**Issue by PhHays** [Typee-Language/Typee#96]
- Create the package in Libs for this first implemented library;
- create the module time.ty;
- start a first programmation of useful functions.

This will help us understand what are the issue we are going to encounter while programming a built-in library in Typee:
- what about embedding targeted code?
- what about genericity over platforms?
- etc.

**Comment by PhHays** [comment]
Done!

**Comment by schmouk** [comment]
Notice: finally renamed SysTime.
